name: velectro-team-manager

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    image: velectro-team-manager-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '3030:3030'
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    image: velectro-team-manager-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend

volumes:
  postgres_data:
